# Generated by Django 3.1 on 2020-08-21 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CovidData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iso_code', models.CharField(max_length=255)),
                ('continent', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('total_cases', models.IntegerField()),
                ('new_cases', models.IntegerField()),
                ('new_cases_smoothed', models.DecimalField(decimal_places=4, max_digits=20)),
                ('total_deaths', models.IntegerField()),
                ('new_deaths', models.IntegerField()),
                ('new_deaths_smoothed', models.DecimalField(decimal_places=4, max_digits=20)),
                ('total_cases_per_million', models.DecimalField(decimal_places=4, max_digits=20)),
                ('new_cases_per_million', models.DecimalField(decimal_places=4, max_digits=20)),
                ('new_cases_smoothed_per_million', models.DecimalField(decimal_places=4, max_digits=20)),
                ('total_deaths_per_million', models.DecimalField(decimal_places=4, max_digits=20)),
                ('new_deaths_per_million', models.DecimalField(decimal_places=4, max_digits=20)),
                ('new_deaths_smoothed_per_million', models.DecimalField(decimal_places=4, max_digits=20)),
                ('new_tests', models.IntegerField()),
                ('total_tests', models.IntegerField()),
                ('total_tests_per_thousand', models.DecimalField(decimal_places=4, max_digits=20)),
                ('new_tests_per_thousand', models.DecimalField(decimal_places=4, max_digits=20)),
                ('new_tests_smoothed', models.DecimalField(decimal_places=4, max_digits=20)),
                ('new_tests_smoothed_per_thousand', models.DecimalField(decimal_places=4, max_digits=20)),
                ('tests_per_case', models.IntegerField()),
                ('positive_rate', models.DecimalField(decimal_places=4, max_digits=20)),
                ('tests_units', models.IntegerField()),
                ('stringency_index', models.DecimalField(decimal_places=4, max_digits=20)),
                ('population', models.IntegerField()),
                ('population_density', models.DecimalField(decimal_places=4, max_digits=20)),
                ('median_age', models.DecimalField(decimal_places=4, max_digits=20)),
                ('aged_65_older', models.DecimalField(decimal_places=4, max_digits=20)),
                ('aged_70_older', models.DecimalField(decimal_places=4, max_digits=20)),
                ('gdp_per_capita', models.DecimalField(decimal_places=4, max_digits=20)),
                ('extreme_poverty', models.DecimalField(decimal_places=4, max_digits=20)),
                ('cardiovasc_death_rate', models.DecimalField(decimal_places=4, max_digits=20)),
                ('diabetes_prevalence', models.DecimalField(decimal_places=4, max_digits=20)),
                ('female_smokers', models.IntegerField()),
                ('male_smokers', models.IntegerField()),
                ('handwashing_facilities', models.IntegerField()),
                ('hospital_beds_per_thousand', models.DecimalField(decimal_places=4, max_digits=20)),
                ('life_expectancy', models.DecimalField(decimal_places=4, max_digits=20)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
