# Generated by Django 3.1 on 2020-08-21 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CovidData',
        ),
    ]
