# Generated by Django 3.1 on 2020-08-23 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0003_auto_20200822_0453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coviddata',
            name='new_cases',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
