# Generated by Django 3.1 on 2020-08-23 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0004_auto_20200823_0216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coviddata',
            name='new_cases_smoothed',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
