from django.db import models

# Create your models here.
class CovidData(models.Model):
    iso_code = models.CharField(max_length=255)
    continent = models.CharField(max_length=255)
    location = models.CharField(max_length=255)
    date = models.DateField()
    total_cases = models.IntegerField()	
    new_cases = models.IntegerField()		
    new_cases_smoothed = models.DecimalField(max_digits=20,decimal_places=4)	
    total_deaths = models.IntegerField()	
    new_deaths = models.IntegerField()	
    new_deaths_smoothed = models.DecimalField(max_digits=20,decimal_places=4)	
    total_cases_per_million	= models.DecimalField(max_digits=20,decimal_places=4)
    new_cases_per_million = models.DecimalField(max_digits=20,decimal_places=4)	
    new_cases_smoothed_per_million = models.DecimalField(max_digits=20,decimal_places=4)	
    total_deaths_per_million = models.DecimalField(max_digits=20,decimal_places=4)	
    new_deaths_per_million = models.DecimalField(max_digits=20,decimal_places=4)	
    new_deaths_smoothed_per_million = models.DecimalField(max_digits=20,decimal_places=4)	
    new_tests = models.IntegerField()	
    total_tests = models.IntegerField()	
    total_tests_per_thousand = models.DecimalField(max_digits=20,decimal_places=4)	
    new_tests_per_thousand = models.DecimalField(max_digits=20,decimal_places=4)	
    new_tests_smoothed = models.DecimalField(max_digits=20,decimal_places=4)	
    new_tests_smoothed_per_thousand = models.DecimalField(max_digits=20,decimal_places=4)	
    tests_per_case = models.IntegerField() 	
    positive_rate = models.DecimalField(max_digits=20,decimal_places=4)	
    tests_units = models.IntegerField()	
    stringency_index = models.DecimalField(max_digits=20,decimal_places=4)	
    population = models.IntegerField()	
    population_density = models.DecimalField(max_digits=20,decimal_places=4)	
    median_age = models.DecimalField(max_digits=20,decimal_places=4)	
    aged_65_older = models.DecimalField(max_digits=20,decimal_places=4)	
    aged_70_older = models.DecimalField(max_digits=20,decimal_places=4)	
    gdp_per_capita = models.DecimalField(max_digits=20,decimal_places=4)	
    extreme_poverty = models.DecimalField(max_digits=20,decimal_places=4)	
    cardiovasc_death_rate = models.DecimalField(max_digits=20,decimal_places=4)	
    diabetes_prevalence = models.DecimalField(max_digits=20,decimal_places=4)	
    female_smokers = models.IntegerField()	
    male_smokers = models.IntegerField()	
    handwashing_facilities = models.IntegerField()	
    hospital_beds_per_thousand = models.DecimalField(max_digits=20,decimal_places=4)	
    life_expectancy = models.DecimalField(max_digits=20,decimal_places=4)
    def __str__(self):
        return self.date
    class Meta:
        ordering = ['date']
